<a href="https://colab.research.google.com/github/YWEI0110/GB885-Assignment-7-Yi-W/blob/main/GB885_Assignment_4_Wei_Yi.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##World Health

In [46]:
#Import the Pandas and NumPy modules
import pandas as pd
import numpy as np

In [47]:
#read csv file of JPG
url="https://raw.githubusercontent.com/katiegaertner/ML-Fundamentals/main/world-health-data-numbers.csv"
df_health=pd.read_csv(url)

In [48]:
#Check the dimensions of the dataset
df_health.shape

(194, 18)

In [49]:
#Preview the dataframe
df_health.head()

,Country,Pop_Density,Abbreviation,Land_Area,Birth_Rate,CO2_Emissions,CPI,Fertility_Rate,GDP,Infant mortality_per_1k,Life_Expectancy,Maternal_Mortality_per_100k,Minimum_Wage,Official Language,oop_health_exp,Physicians_per_1k,Population,Unemployment_Rate
0,Andorra,164.0,AD,468.0,7.20,469.0,NaN,1.27,3.154058e+09,2.7,NaN,NaN,6.63,Catalan,0.36,3.33,77142.0,NaN
1,United Arab Emirates,118.0,AE,83600.0,10.33,206324.0,114.52,1.41,4.211420e+11,6.5,77.8,3.0,NaN,Arabic,0.18,2.53,9770529.0,0.02
2,Afghanistan,60.0,AF,652230.0,32.49,8672.0,149.90,4.47,1.910135e+10,47.9,64.5,638.0,0.43,Pashto,0.78,0.28,38041754.0,0.11
3,Antigua and Barbuda,223.0,AG,443.0,15.33,557.0,113.81,1.99,1.727759e+09,5.0,76.9,42.0,3.04,English,0.24,2.76,97118.0,NaN
4,Albania,105.0,AL,28748.0,11.78,4536.0,119.05,1.62,1.527808e+10,7.8,78.5,15.0,1.12,Albanian,0.57,1.20,2854191.0,0.12

###Update code

In [50]:
#set Abbreviation as index
df_health = df_health.set_index("Abbreviation")
df_health.head()

,Country,Pop_Density,Land_Area,Birth_Rate,CO2_Emissions,CPI,Fertility_Rate,GDP,Infant mortality_per_1k,Life_Expectancy,Maternal_Mortality_per_100k,Minimum_Wage,Official Language,oop_health_exp,Physicians_per_1k,Population,Unemployment_Rate
Abbreviation,,,,,,,,,,,,,,,,,
AD,Andorra,164.0,468.0,7.20,469.0,NaN,1.27,3.154058e+09,2.7,NaN,NaN,6.63,Catalan,0.36,3.33,77142.0,NaN
AE,United Arab Emirates,118.0,83600.0,10.33,206324.0,114.52,1.41,4.211420e+11,6.5,77.8,3.0,NaN,Arabic,0.18,2.53,9770529.0,0.02
AF,Afghanistan,60.0,652230.0,32.49,8672.0,149.90,4.47,1.910135e+10,47.9,64.5,638.0,0.43,Pashto,0.78,0.28,38041754.0,0.11
AG,Antigua and Barbuda,223.0,443.0,15.33,557.0,113.81,1.99,1.727759e+09,5.0,76.9,42.0,3.04,English,0.24,2.76,97118.0,NaN
AL,Albania,105.0,28748.0,11.78,4536.0,119.05,1.62,1.527808e+10,7.8,78.5,15.0,1.12,Albanian,0.57,1.20,2854191.0,0.12

In [52]:
#Search nation index value "DZ"
df_health.loc["DZ"]

Country                               Algeria
Pop_Density                              18.0
Land_Area                           2381741.0
Birth_Rate                              24.28
CO2_Emissions                        150006.0
CPI                                    151.36
Fertility_Rate                           3.02
GDP                            169988000000.0
Infant mortality_per_1k                  20.1
Life_Expectancy                          76.7
Maternal_Mortality_per_100k             112.0
Minimum_Wage                             0.95
Official Language                      Arabic
oop_health_exp                           0.28
Physicians_per_1k                        1.72
Population                         43053054.0
Unemployment_Rate                        0.12
Name: DZ, dtype: object

###Update code

In [53]:
#drop Vatican City (abbreviation 'VA') from DataFrame.
df_health = df_health.drop("VA")
df_health.shape

(193, 17)

In [68]:
#Search the official language of the nation on the 186th row
df_health.sort_values(by="Abbreviation")
df_health.iloc[185][["Country", "Official Language"]]

Country              San Marino
Official Language       Italian
Name: SM, dtype: object

In [55]:
#Sort infant mortality from highest to lowest
df_health = df_health.sort_values("Infant mortality_per_1k", ascending=False)
df_health.head(10)

,Country,Pop_Density,Land_Area,Birth_Rate,CO2_Emissions,CPI,Fertility_Rate,GDP,Infant mortality_per_1k,Life_Expectancy,Maternal_Mortality_per_100k,Minimum_Wage,Official Language,oop_health_exp,Physicians_per_1k,Population,Unemployment_Rate
Abbreviation,,,,,,,,,,,,,,,,,
CF,Central African Republic,8.0,622984.0,35.35,297.0,186.86,4.72,2.220307e+09,84.5,52.8,829.0,0.37,French,0.40,0.06,4745185.0,0.04
SL,Sierra Leone,111.0,71740.0,33.41,1093.0,234.16,4.26,3.941474e+09,78.5,54.3,1120.0,0.57,English,0.38,0.03,7813215.0,0.04
SO,Somalia,25.0,637657.0,41.75,645.0,NaN,6.07,4.720727e+09,76.6,57.1,829.0,NaN,Arabic,NaN,0.02,15442905.0,0.11
NG,Nigeria,226.0,923768.0,37.91,120369.0,267.51,5.39,4.481200e+11,75.7,54.3,917.0,0.54,English,0.72,0.38,200963599.0,0.08
TD,Chad,13.0,1284000.0,42.17,1016.0,117.70,5.75,1.131495e+10,71.4,54.0,1140.0,0.60,French,0.56,0.04,15946876.0,0.02
CD,Democratic Republic of the Congo,40.0,2344858.0,41.18,2021.0,133.85,5.92,4.731962e+10,68.2,60.4,473.0,0.18,French,0.37,0.07,86790567.0,0.04
LS,Lesotho,71.0,30355.0,26.81,2512.0,155.86,3.14,2.460072e+09,65.7,53.7,544.0,0.41,English,0.17,0.07,2125268.0,0.23
GN,Guinea,53.0,245857.0,36.36,2996.0,262.95,4.70,1.359028e+10,64.9,61.2,576.0,NaN,French,0.55,0.08,12771246.0,0.04
SS,South Sudan,18.0,644329.0,35.01,1727.0,4583.71,4.70,1.199780e+10,63.7,57.6,1150.0,NaN,English,0.61,NaN,11062113.0,0.12
GQ,Equatorial Guinea,50.0,28051.0,33.24,5655.0,124.35,4.51,1.102677e+10,62.6,58.4,301.0,1.05,Spanish,0.72,0.40,1355986.0,0.06

###Create a dataframe

In [56]:
#Create a dataframe for Spanish-speaking nations
spanish_speaking_countries = df_health[df_health["Official Language"] == "Spanish"]

#Check the number of rows and columns of new dataframe
spanish_speaking_countries.shape

(19, 17)

In [57]:
#calculate mean of infant mortality in new dataframe
round(spanish_speaking_countries["Infant mortality_per_1k"].mean(), 2)

np.float64(15.56)

In [58]:
#Calculate median maternal mortality in countries whose official language is Spanish
round(spanish_speaking_countries["Maternal_Mortality_per_100k"].median(), 2)

65.0

In [59]:
#Create a new column for GDP per capita
df_health["GDP_per_capita"] = df_health["GDP"] / df_health["Population"]

# Sort from highest to lowest GDP per capita
gdp_per_capita_sorted = df_health.sort_values("GDP_per_capita", ascending=False)

#find nation with fourth-highest GDP per capita.
gdp_per_capita_sorted.iloc[3]["Country"]

'Switzerland'

In [60]:
#Find the maternal mortality rate for Switzerland
round(gdp_per_capita_sorted.iloc[3]["Maternal_Mortality_per_100k"], 2)

np.float64(5.0)

In [61]:
#Calculate the average maternal mortality rate per 100,000 for all nations
round(df_health["Maternal_Mortality_per_100k"].mean(), 2)

np.float64(160.39)

In [62]:
# Find the country with the lowest infant mortality and its out-of-pocket health care percentage

lowest_infant_mortality = df_health.sort_values("Infant mortality_per_1k", ascending=True).iloc[0]

round(lowest_infant_mortality["oop_health_exp"] * 100, 2)

np.float64(20.0)

In [63]:
# Get the out-of-pocket health care percentage for the country with the highest reported infant mortality

highest_infant_mortality = df_health.dropna(subset=["Infant mortality_per_1k"]) \
    .sort_values("Infant mortality_per_1k", ascending=False) \
    .iloc[0]

round(highest_infant_mortality["oop_health_exp"] * 100, 2)

np.float64(40.0)